Assets/Scenes/SampleScene.unity
Assets/Scripts/Bullet.cs
Assets/Scripts/PlayerMovement.cs

Add function for bullet recycling and show current collectibles. 
The player can turn the same color bullets into resources. 
Show collected resources on UI.

Add Bullet Recycling to Collectables

---

Assets/Scenes/GameOver.unity
Assets/Scenes/GameOver.unity.meta
Assets/Scripts/PlayerMovement.cs
Assets/Scripts/SceneLoader.cs
Assets/Scripts/SceneLoader.cs.meta

Add GameOver scene

---

Assets/Prefab/Healthbar.prefab
Assets/Scenes/SampleScene.unity
Assets/Scripts/.idea/.idea.Scripts.dir/.idea/vcs.xml
Assets/Scripts/PlayerMovement.cs

1. Debugged: the timer will not reset when loading a new scene.
2. Move HP text and bar together.

1. Fix bug: timer resetting problem. 2. Integrate HP number & bar

---

Assets/Prefab/Wall.prefab
Assets/Prefab/Wall.prefab.meta
Assets/Scenes/Level2.unity
Assets/Scenes/Level2.unity.meta

[Level] add level1 & level2 map

---

Assets/Scripts/Bullet.cs
Assets/Scripts/PlayerMovement.cs

Add endless

---

Assets/Scenes/SampleScene.unity
Assets/Scripts/DataManager.cs
Assets/Scripts/DataManager.cs.meta
Assets/Scripts/PlayerMovement.cs

1. Create DataManager to submit playtest data to google form
2. Collecting endless game time

Add Endless data collection functionality

---

Assets/Prefab/WarnText.prefab
Assets/Prefab/WarnText.prefab.meta
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scripts/LV_PlayerMovement.cs
Assets/Scripts/WarnText.cs
Assets/Scripts/WarnText.cs.meta

Add warning before player changes color for level mode

Add waarning text

---

Assets/Prefab/Bullet_Generator.prefab
Assets/Prefab/Bullet_Generator.prefab.meta
Assets/Scenes/LV_GameOver.unity
Assets/Scenes/LV_GameOver.unity.meta
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scenes/Menu.unity
Assets/Scripts/EndpointOnTrigger.cs
Assets/Scripts/LV_Bullet.cs
Assets/Scripts/LV_BulletGenerator.cs
Assets/Scripts/LV_BulletGenerator.cs.meta
Assets/Scripts/LV_GameManager.cs
Assets/Scripts/LV_GameManager.cs.meta
Assets/Scripts/LV_GameOverManager.cs
Assets/Scripts/LV_GameOverManager.cs.meta
Assets/Scripts/LV_PlayerMovement.cs

Add bullet generator and wall prefabs for Level 1 and Level 2.

Add level1&2 bullet

---

Assets/Prefab/UI_States.prefab
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scenes/Level2_Backup.unity
Assets/Scenes/Level3.unity
Assets/Scripts/LV_PlayerMovement.cs

Add change color hint on top left corner

Add change color hint 

---

Assets/Scripts/Bullet.cs
Assets/Scripts/PlayerMovement.cs

Endless modify bullet speed and player change rate.

Endless modify bullet speed and player change rate

---

Assets/Scenes/Level0.unity
Assets/Scenes/Level0.unity.meta
Assets/Scenes/LevelMenu.unity
Assets/Scripts/LV_Bullet.cs
Assets/Scripts/LV_PlayerMovement.cs
Assets/Scripts/LV_TutorialManager.cs
Assets/Scripts/LV_TutorialManager.cs.meta

Level tutorial

---

Assets/Scenes/Level0.unity

* Adjust level0 bullet speed since the original one was too slow for WebGL

adjust level0 bullet speed

---

Assets/Scenes/SampleScene.unity
Assets/Scripts/PlayerMovement.cs

Add endless boundary: 4 walls, and change player Circle collider 2D is Trigger to empty.

Add endless boundary

---

Assets/Prefab/UI_States.prefab
Assets/Scenes/Level2.unity
Assets/Scripts/LV_PlayerMovement.cs

Reverts BrianPHChen/training99#48

Revert "Level2 improvement"

---

Assets/Scripts/LV_PlayerMovement.cs
ProjectSettings/EditorBuildSettings.asset

1. player can change color themselves with a 3 second cool down
2. add hp if collect red items
3. player shrinks if collect yellow items

Add player change color themselves and red and yellow features

---

Assets/Scenes/Level3.unity

modify level 3 map

---

Assets/Scenes/Level2.unity

modify level 2 map

---

Assets/Scenes/SampleScene.unity
Assets/Scripts/PlayerMovement.cs

show next color in endless mode

indicate next color in endless mode

---

Assets/Prefab/UI_States.prefab
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scenes/Level3.unity
Assets/Scenes/Level4.unity
Assets/Scenes/Level5.unity
Assets/Scripts/EndpointOnTrigger.cs
Assets/Scripts/KeyOnTrigger.cs
Assets/Scripts/LV_PlayerMovement.cs
Assets/Scripts/ProgressBar.cs
Assets/Scripts/ProgressBar.cs.meta

* Add progress bar on UI_States prefab.
* Update leve1-5 scene.

Add level mode progress bar

---

Assets/Prefab/BulletCircle.prefab
Assets/Prefab/BulletSquare.prefab
Assets/Prefab/LV_Player.prefab
Assets/Scenes/Level0.unity
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scenes/Level3.unity
Assets/Scenes/Level4.unity
Assets/Scenes/Level5.unity
Assets/Scenes/Level6.unity
Assets/Scenes/Level7.unity
Assets/Scenes/SampleScene.unity
Assets/Scripts/LV_BulletPatrol.cs
Assets/Scripts/LV_TutorialManager.cs
Assets/Scripts/LevelMode.meta

* Level mode unify all bullets speed in all levels
* Change bullet colors

Change bullet color and unify bullet speed

---

Assets/Scripts/Bullet.cs

fix boundary bugs and modify difficulty.

fix boundary bugs and modify difficulty.

---

Assets/Scenes/Level0.unity
Assets/Scenes/Level1.unity
Assets/Scenes/Level2.unity
Assets/Scenes/Level3.unity
Assets/Scenes/Level4.unity
Assets/Scenes/Level5.unity
Assets/Scenes/Level6.unity
Assets/Scenes/Level7.unity
ProjectSettings/Packages/com.unity.connect.share/Settings.json

Change level mode's tutorial according to GDD

Level tutorial improvement

---

Assets/Prefab/UI_ActiveSkills.prefab
Assets/Scenes/Level5.unity
Assets/Scenes/Level6.unity
Assets/Scenes/Level7.unity

* Change to collect 2 instead of 4 blue to enable pass wall skill

collect 2 blue to enable pass wall skill

---

Assets/Prefab/WallCross.prefab
Assets/Scenes/Level5.unity
Assets/Scenes/Level6.unity
Assets/Scenes/Level7.unity
Assets/Scripts/LV_CrossWall.cs

* Add different color walls in level 5,6,7

add different color walls

---

Assets/Scripts/LevelMode/LV_PlayerMovement.cs

modify circle ability

---

Assets/Scripts/LevelMode/LV_PlayerMovement.cs

level menu UI update
